### ISSUE TITLE
PlumX Plugin that supports OJS 3.2X

### ISSUE THREAD

**Issue by sergiobmartins** [ulsdevteam/ojs-plum-plugin#8]
Hi @ctgraham, @monicalpaiva, I installed the latest version of this plugin to see if will work in OJS 3.2.0.3. It worked to install it via upload a new plugin, but when click in Settings, it showns an error "Failed Ajax request or invalid JSON returned.". Please, do you have any idea how to fix it?

**Comment by ctgraham** [comment]
We did some preliminary testing which showed compatibility with OJS 3.2.0-0 in May, but haven't done full testing or certification yet.

If you can share any messages from your error log, and are willing to test the plugin pre-release, we may be able to address the failures sooner rather than later.

Current plans are to pick up work on plugin compatibility for 3.2 again this fall.

**Comment by ainulrafiq** [comment]
Dear everyone, are there any updates about this compatibility?

Thanks!

**Comment by ctgraham** [comment]
The Plum Analytics plugin was certified for 3.2 and should be available in the plugin gallery as of December 7.
https://github.com/pkp/plugin-gallery/pull/13

If you find any issues specific to the use of the plugin with 3.2, please feel free to describe them here.

**Comment by ainulrafiq** [comment]
Dear all,
We are using the plugin now, I downloaded the gzip format from the master, and it looks very good https://myjurnal.poltekkes-kdi.ac.id/index.php/HIJP/article/view/125 .

Thank you!
